package android

import (
	"fmt"
	"io"
	"strconv"
	"strings"

	"github.com/odvcencio/gosx-native/emit/shared"
	"github.com/odvcencio/gosx/nir"
)

// Emit writes Jetpack Compose Kotlin source for every component in mod.
func Emit(mod *nir.Module, w io.Writer) error {
	fmt.Fprintln(w, "// Code generated by gsxnative. DO NOT EDIT.")
	fmt.Fprintln(w, "package generated")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "import androidx.compose.foundation.layout.Column")
	fmt.Fprintln(w, "import androidx.compose.foundation.layout.Row")
	fmt.Fprintln(w, "import androidx.compose.material3.Button")
	if moduleHasTag(mod, "checkbox") {
		fmt.Fprintln(w, "import androidx.compose.material3.Checkbox")
	}
	fmt.Fprintln(w, "import androidx.compose.material3.Text")
	if moduleHasTag(mod, "textinput") || moduleHasTag(mod, "textarea") {
		fmt.Fprintln(w, "import androidx.compose.material3.TextField")
	}
	fmt.Fprintln(w, "import androidx.compose.runtime.Composable")
	fmt.Fprintln(w, "import androidx.compose.runtime.getValue")
	fmt.Fprintln(w, "import androidx.compose.runtime.setValue")
	if moduleHasHandlerEvent(mod, "key") {
		fmt.Fprintln(w, "import androidx.compose.ui.Modifier")
		fmt.Fprintln(w, "import androidx.compose.ui.input.key.key")
		fmt.Fprintln(w, "import androidx.compose.ui.input.key.onKeyEvent")
	}
	fmt.Fprintln(w, "import com.gosx.nativekit.GSXComponent")
	fmt.Fprintln(w, "import com.gosx.nativekit.rememberGSXSignal")
	fmt.Fprintln(w)
	for i, c := range mod.Components {
		if i > 0 {
			fmt.Fprintln(w)
		}
		if err := emitComponent(w, c); err != nil {
			return err
		}
	}
	return nil
}

func moduleHasTag(mod *nir.Module, tag string) bool {
	for _, c := range mod.Components {
		if viewHasTag(c.Body, tag) {
			return true
		}
	}
	return false
}

func viewHasTag(v nir.View, tag string) bool {
	switch n := v.(type) {
	case *nir.Element:
		if n.Tag == tag {
			return true
		}
		for _, child := range n.Children {
			if viewHasTag(child, tag) {
				return true
			}
		}
	case *nir.Conditional:
		for _, child := range n.Then {
			if viewHasTag(child, tag) {
				return true
			}
		}
		for _, child := range n.Else {
			if viewHasTag(child, tag) {
				return true
			}
		}
	case *nir.ComponentRef:
		for _, child := range n.Children {
			if viewHasTag(child, tag) {
				return true
			}
		}
	case *nir.Loop:
		for _, child := range n.Body {
			if viewHasTag(child, tag) {
				return true
			}
		}
		for _, child := range n.Empty {
			if viewHasTag(child, tag) {
				return true
			}
		}
	}
	return false
}

func moduleHasHandlerEvent(mod *nir.Module, event string) bool {
	for _, c := range mod.Components {
		if viewHasHandlerEvent(c.Body, event) {
			return true
		}
	}
	return false
}

func viewHasHandlerEvent(v nir.View, event string) bool {
	switch n := v.(type) {
	case *nir.Element:
		for _, handler := range n.Handlers {
			if handler.Event == event {
				return true
			}
		}
		for _, child := range n.Children {
			if viewHasHandlerEvent(child, event) {
				return true
			}
		}
	case *nir.Conditional:
		for _, child := range n.Then {
			if viewHasHandlerEvent(child, event) {
				return true
			}
		}
		for _, child := range n.Else {
			if viewHasHandlerEvent(child, event) {
				return true
			}
		}
	case *nir.ComponentRef:
		for _, child := range n.Children {
			if viewHasHandlerEvent(child, event) {
				return true
			}
		}
	case *nir.Loop:
		for _, child := range n.Body {
			if viewHasHandlerEvent(child, event) {
				return true
			}
		}
		for _, child := range n.Empty {
			if viewHasHandlerEvent(child, event) {
				return true
			}
		}
	}
	return false
}

func emitComponent(w io.Writer, c *nir.Component) error {
	if c.Props != nil {
		fmt.Fprintf(w, "data class %sProps(\n", c.Name)
		for i, f := range c.Props.Fields {
			sep := ","
			if i == len(c.Props.Fields)-1 {
				sep = ""
			}
			fmt.Fprintf(w, "    val %s: %s%s\n", f.Name, kotlinType(f.Type), sep)
		}
		fmt.Fprintln(w, ")")
		fmt.Fprintln(w)
	}
	fmt.Fprintln(w, "@GSXComponent")
	fmt.Fprintln(w, "@Composable")
	fmt.Fprintf(w, "fun %s(props: %sProps) {\n", c.Name, c.Name)
	for _, sig := range c.Signals {
		fmt.Fprintf(w, "    var %s by rememberGSXSignal(%s)\n", sig.Name, emitRxExpr(sig.Init))
	}
	for _, computed := range c.Computeds {
		fmt.Fprintf(w, "    val %s = %s\n", computed.Name, emitRxExpr(computed.Body))
	}
	if len(c.Signals) > 0 || len(c.Computeds) > 0 {
		fmt.Fprintln(w)
	}
	fmt.Fprintf(w, "%s\n", emitView(c.Body, 1))
	fmt.Fprintln(w, "}")
	return nil
}

func emitView(v nir.View, indent int) string {
	pad := strings.Repeat("    ", indent)
	switch n := v.(type) {
	case *nir.Element:
		if n.Tag == "text" {
			return pad + emitTextElement(n)
		}
		if n.Tag == "textinput" {
			return pad + emitTextInput(n, indent, false)
		}
		if n.Tag == "textarea" {
			return pad + emitTextInput(n, indent, true)
		}
		if n.Tag == "checkbox" {
			return pad + emitCheckbox(n, indent)
		}
		if n.Tag == "select" {
			return emitSelect(n, indent)
		}
		for _, h := range n.Handlers {
			if h.Event == "tap" {
				var sb strings.Builder
				sb.WriteString(pad)
				sb.WriteString("Button(onClick = { ")
				sb.WriteString(emitRxBlock(h.Body))
				sb.WriteString(" }) {\n")
				sb.WriteString(strings.Repeat("    ", indent+1))
				sb.WriteString("Text(text = ")
				sb.WriteString(kotlinQuote(emitChildrenInline(n.Children)))
				sb.WriteString(")\n")
				sb.WriteString(pad)
				sb.WriteString("}")
				return sb.String()
			}
		}
		tag := shared.ComposeTag(n.Tag)
		if tag == "" {
			return pad + "/* unsupported tag: " + n.Tag + " */"
		}
		var sb strings.Builder
		sb.WriteString(pad)
		sb.WriteString(tag)
		sb.WriteString(" {\n")
		for _, child := range n.Children {
			sb.WriteString(emitView(child, indent+1))
			sb.WriteByte('\n')
		}
		sb.WriteString(pad)
		sb.WriteString("}")
		return sb.String()
	case *nir.Text:
		return pad + "Text(text = " + kotlinQuote(n.Value) + ")"
	case *nir.ExprHole:
		return pad + `Text(text = "${` + emitRxExpr(&n.Expr) + `}")`
	case *nir.Conditional:
		return emitConditional(n, indent)
	case *nir.ComponentRef:
		return pad + emitComponentRef(n)
	case *nir.Loop:
		return emitLoop(n, indent)
	default:
		return pad + "/* unsupported view */"
	}
}

func emitComponentRef(n *nir.ComponentRef) string {
	props := make([]string, len(n.Props))
	for i := range n.Props {
		props[i] = fmt.Sprintf("%s = %s", n.Props[i].Name, emitRxExpr(&n.Props[i].Value))
	}
	return fmt.Sprintf("%s(props = %sProps(%s))", n.Name, n.Name, strings.Join(props, ", "))
}

func emitLoop(n *nir.Loop, indent int) string {
	pad := strings.Repeat("    ", indent)
	itemName := n.ItemName
	if itemName == "" {
		itemName = "item"
	}
	var sb strings.Builder
	sb.WriteString(pad)
	sb.WriteString(emitRxExpr(&n.Items))
	sb.WriteString(".forEach { ")
	sb.WriteString(itemName)
	sb.WriteString(" ->\n")
	for _, child := range n.Body {
		sb.WriteString(emitView(child, indent+1))
		sb.WriteByte('\n')
	}
	sb.WriteString(pad)
	sb.WriteString("}")
	return sb.String()
}

func emitConditional(n *nir.Conditional, indent int) string {
	pad := strings.Repeat("    ", indent)
	var sb strings.Builder
	sb.WriteString(pad)
	sb.WriteString("if (")
	sb.WriteString(emitRxExpr(&n.Condition))
	sb.WriteString(") {\n")
	for _, child := range n.Then {
		sb.WriteString(emitView(child, indent+1))
		sb.WriteByte('\n')
	}
	if len(n.Else) > 0 {
		sb.WriteString(pad)
		sb.WriteString("} else {\n")
		for _, child := range n.Else {
			sb.WriteString(emitView(child, indent+1))
			sb.WriteByte('\n')
		}
	}
	sb.WriteString(pad)
	sb.WriteString("}")
	return sb.String()
}

func emitTextInput(n *nir.Element, indent int, multiline bool) string {
	pad := strings.Repeat("    ", indent)
	childPad := strings.Repeat("    ", indent+1)
	grandchildPad := strings.Repeat("    ", indent+2)
	value := attrExpr(n, "value")
	if value == nil {
		value = &nir.RxExpr{Kind: "literal", Literal: &nir.Literal{Type: "string", Value: ""}}
	}
	var handler *nir.Handler
	for i := range n.Handlers {
		if n.Handlers[i].Event == "input" || n.Handlers[i].Event == "change" {
			handler = &n.Handlers[i]
			break
		}
	}
	onValueChange := "{ _ -> }"
	if handler != nil {
		onValueChange = "{ eventValue -> " + emitRxBlockWithEventBindings(handler.Body, eventBindings{"value": "eventValue"}) + " }"
	}
	var sb strings.Builder
	sb.WriteString("TextField(\n")
	sb.WriteString(childPad)
	sb.WriteString("value = ")
	sb.WriteString(emitRxExpr(value))
	sb.WriteString(",\n")
	sb.WriteString(childPad)
	sb.WriteString("onValueChange = ")
	sb.WriteString(onValueChange)
	if keyHandler := handlerForEvent(n, "key"); keyHandler != nil {
		sb.WriteString(",\n")
		sb.WriteString(childPad)
		sb.WriteString("modifier = Modifier.onKeyEvent { event ->\n")
		sb.WriteString(grandchildPad)
		sb.WriteString("val eventKey = event.key.toString()\n")
		sb.WriteString(grandchildPad)
		sb.WriteString(emitRxBlockWithEventBindings(keyHandler.Body, eventBindings{"key": "eventKey"}))
		sb.WriteByte('\n')
		sb.WriteString(grandchildPad)
		sb.WriteString("false\n")
		sb.WriteString(childPad)
		sb.WriteString("}")
	}
	if placeholder := literalAttr(n, "placeholder"); placeholder != "" {
		sb.WriteString(",\n")
		sb.WriteString(childPad)
		sb.WriteString("placeholder = { Text(text = ")
		sb.WriteString(kotlinQuote(placeholder))
		sb.WriteString(") }")
	}
	if multiline {
		sb.WriteString(",\n")
		sb.WriteString(childPad)
		sb.WriteString("minLines = 3")
	}
	sb.WriteByte('\n')
	sb.WriteString(pad)
	sb.WriteString(")")
	return sb.String()
}

func emitCheckbox(n *nir.Element, indent int) string {
	pad := strings.Repeat("    ", indent)
	childPad := strings.Repeat("    ", indent+1)
	checked := attrExpr(n, "checked")
	if checked == nil {
		checked = &nir.RxExpr{Kind: "literal", Literal: &nir.Literal{Type: "bool", Value: "false"}}
	}
	onCheckedChange := "{ _ -> }"
	for _, h := range n.Handlers {
		if h.Event == "change" || h.Event == "input" {
			onCheckedChange = "{ eventChecked -> " + emitRxBlockWithEventBindings(h.Body, eventBindings{"checked": "eventChecked"}) + " }"
			break
		}
	}
	var sb strings.Builder
	sb.WriteString("Checkbox(\n")
	sb.WriteString(childPad)
	sb.WriteString("checked = ")
	sb.WriteString(emitRxExpr(checked))
	sb.WriteString(",\n")
	sb.WriteString(childPad)
	sb.WriteString("onCheckedChange = ")
	sb.WriteString(onCheckedChange)
	sb.WriteByte('\n')
	sb.WriteString(pad)
	sb.WriteString(")")
	return sb.String()
}

func emitSelect(n *nir.Element, indent int) string {
	pad := strings.Repeat("    ", indent)
	childPad := strings.Repeat("    ", indent+1)
	grandchildPad := strings.Repeat("    ", indent+2)
	greatGrandchildPad := strings.Repeat("    ", indent+3)
	selection := attrExpr(n, "selectedIndex")
	if selection == nil {
		selection = &nir.RxExpr{Kind: "literal", Literal: &nir.Literal{Type: "int", Value: "0"}}
	}
	onClick := "{}"
	if handler := handlerForEvent(n, "change"); handler != nil {
		onClick = "{ " + emitRxBlockWithEventBindings(handler.Body, eventBindings{"selectedIndex": "eventSelectedIndex"}) + " }"
	}
	var sb strings.Builder
	sb.WriteString(pad)
	sb.WriteString("Column {\n")
	sb.WriteString(childPad)
	sb.WriteString("listOf(")
	labels := optionLabels(n.Children)
	for i, label := range labels {
		if i > 0 {
			sb.WriteString(", ")
		}
		sb.WriteString(kotlinQuote(label))
	}
	sb.WriteString(").forEachIndexed { eventSelectedIndex, option ->\n")
	sb.WriteString(grandchildPad)
	sb.WriteString("Button(onClick = ")
	sb.WriteString(onClick)
	sb.WriteString(") {\n")
	sb.WriteString(greatGrandchildPad)
	sb.WriteString("Text(text = if (eventSelectedIndex == ")
	sb.WriteString(emitRxExpr(selection))
	sb.WriteString(") \"$option (selected)\" else option)\n")
	sb.WriteString(grandchildPad)
	sb.WriteString("}\n")
	sb.WriteString(childPad)
	sb.WriteString("}\n")
	sb.WriteString(pad)
	sb.WriteString("}")
	return sb.String()
}

func emitTextElement(n *nir.Element) string {
	if len(n.Children) == 0 {
		return `Text(text = "")`
	}
	if len(n.Children) == 1 {
		switch child := n.Children[0].(type) {
		case *nir.Text:
			return "Text(text = " + kotlinQuote(child.Value) + ")"
		case *nir.ExprHole:
			return `Text(text = "${` + emitRxExpr(&child.Expr) + `}")`
		}
	}
	return "Text(text = " + kotlinQuote(emitChildrenInline(n.Children)) + ")"
}

func handlerForEvent(n *nir.Element, event string) *nir.Handler {
	for i := range n.Handlers {
		if n.Handlers[i].Event == event {
			return &n.Handlers[i]
		}
	}
	return nil
}

func optionLabels(children []nir.View) []string {
	labels := make([]string, 0, len(children))
	for _, child := range children {
		option, ok := child.(*nir.Element)
		if !ok || option.Tag != "option" {
			continue
		}
		labels = append(labels, emitChildrenInline(option.Children))
	}
	return labels
}

func emitChildrenInline(children []nir.View) string {
	var sb strings.Builder
	for _, child := range children {
		switch n := child.(type) {
		case *nir.Text:
			sb.WriteString(n.Value)
		case *nir.ExprHole:
			sb.WriteString("${")
			sb.WriteString(emitRxExpr(&n.Expr))
			sb.WriteString("}")
		}
	}
	return sb.String()
}

type eventBindings map[string]string

func (b eventBindings) ref(ref string) (string, bool) {
	if !strings.HasPrefix(ref, "event.") {
		return "", false
	}
	value := b[strings.TrimPrefix(ref, "event.")]
	return value, value != ""
}

func emitRxExpr(e *nir.RxExpr) string {
	return emitRxExprWithEventBindings(e, nil)
}

func emitRxExprWithEventBindings(e *nir.RxExpr, bindings eventBindings) string {
	if e == nil {
		return ""
	}
	switch e.Kind {
	case "literal":
		if e.Literal == nil {
			return ""
		}
		if e.Literal.Type == "string" {
			return kotlinQuote(e.Literal.Value)
		}
		return e.Literal.Value
	case "ref":
		if value, ok := bindings.ref(e.Ref); ok {
			return value
		}
		return e.Ref
	case "binop":
		if e.BinOp == nil {
			return ""
		}
		return fmt.Sprintf("%s %s %s", emitRxExprWithEventBindings(&e.BinOp.Left, bindings), e.BinOp.Op, emitRxExprWithEventBindings(&e.BinOp.Right, bindings))
	case "cond":
		if e.Cond == nil {
			return ""
		}
		return fmt.Sprintf(
			"(if (%s) %s else %s)",
			emitRxExprWithEventBindings(&e.Cond.Condition, bindings),
			emitRxExprWithEventBindings(&e.Cond.Then, bindings),
			emitRxExprWithEventBindings(&e.Cond.Else, bindings),
		)
	case "call":
		if e.Call == nil {
			return ""
		}
		return emitCall(e.Call, bindings)
	default:
		return ""
	}
}

func emitCall(c *nir.Call, bindings eventBindings) string {
	args := make([]string, len(c.Args))
	for i := range c.Args {
		args[i] = emitRxExprWithEventBindings(&c.Args[i], bindings)
	}
	if len(args) == 0 {
		return c.Callee + "()"
	}
	receiver := args[0]
	switch c.Callee {
	case "len":
		return receiver + ".count()"
	case "upper":
		return receiver + ".uppercase()"
	case "lower":
		return receiver + ".lowercase()"
	case "trim":
		return receiver + ".trim()"
	case "split":
		if len(args) != 2 {
			return receiver
		}
		return receiver + ".split(" + args[1] + ")"
	case "join":
		if len(args) != 2 {
			return receiver
		}
		return receiver + ".joinToString(separator = " + args[1] + ")"
	case "replace":
		if len(args) != 3 {
			return receiver
		}
		return receiver + ".replace(" + args[1] + ", " + args[2] + ")"
	case "substring":
		if len(args) != 3 {
			return receiver
		}
		return receiver + ".substring(" + args[1] + ", " + args[2] + ")"
	case "startsWith":
		if len(args) != 2 {
			return receiver
		}
		return receiver + ".startsWith(" + args[1] + ")"
	case "endsWith":
		if len(args) != 2 {
			return receiver
		}
		return receiver + ".endsWith(" + args[1] + ")"
	case "contains":
		if len(args) != 2 {
			return receiver
		}
		return receiver + ".contains(" + args[1] + ")"
	case "toString":
		return receiver + ".toString()"
	case "toInt":
		return "(" + receiver + ".toIntOrNull() ?: 0)"
	case "toFloat":
		return "(" + receiver + ".toDoubleOrNull() ?: 0.0)"
	default:
		return fmt.Sprintf("%s(%s)", c.Callee, strings.Join(args, ", "))
	}
}

func emitRxBlock(b nir.RxBlock) string {
	return emitRxBlockWithEventBindings(b, nil)
}

func emitRxBlockWithEventBindings(b nir.RxBlock, bindings eventBindings) string {
	parts := make([]string, 0, len(b.Stmts))
	for _, s := range b.Stmts {
		switch s.Kind {
		case "expr":
			parts = append(parts, emitRxExprWithEventBindings(s.Expr, bindings))
		case "signal_set":
			parts = append(parts, fmt.Sprintf("%s = %s", s.Target, emitRxExprWithEventBindings(s.Value, bindings)))
		}
	}
	return strings.Join(parts, "; ")
}

func kotlinType(swiftType string) string {
	if strings.HasPrefix(swiftType, "[") && strings.HasSuffix(swiftType, "]") {
		inner := strings.TrimSuffix(strings.TrimPrefix(swiftType, "["), "]")
		return "List<" + kotlinType(inner) + ">"
	}
	switch swiftType {
	case "Bool":
		return "Boolean"
	case "String", "Int", "Double", "Float":
		return swiftType
	default:
		return swiftType
	}
}

func kotlinQuote(s string) string {
	return strconv.Quote(s)
}

func attrExpr(n *nir.Element, name string) *nir.RxExpr {
	for i := range n.Attrs {
		if n.Attrs[i].Name == name {
			return &n.Attrs[i].Value
		}
	}
	return nil
}

func literalAttr(n *nir.Element, name string) string {
	expr := attrExpr(n, name)
	if expr == nil || expr.Kind != "literal" || expr.Literal == nil {
		return ""
	}
	return expr.Literal.Value
}
