package android

import (
	"fmt"
	"io"
	"strconv"
	"strings"

	"github.com/odvcencio/gosx-native/emit/shared"
	"github.com/odvcencio/gosx/nir"
)

// Emit writes Jetpack Compose Kotlin source for every component in mod.
func Emit(mod *nir.Module, w io.Writer) error {
	fmt.Fprintln(w, "// Code generated by gsxnative. DO NOT EDIT.")
	fmt.Fprintln(w, "package generated")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "import androidx.compose.foundation.layout.Column")
	fmt.Fprintln(w, "import androidx.compose.foundation.layout.Row")
	fmt.Fprintln(w, "import androidx.compose.material3.Button")
	fmt.Fprintln(w, "import androidx.compose.material3.Text")
	fmt.Fprintln(w, "import androidx.compose.runtime.Composable")
	fmt.Fprintln(w, "import androidx.compose.runtime.getValue")
	fmt.Fprintln(w, "import androidx.compose.runtime.setValue")
	fmt.Fprintln(w, "import com.gosx.nativekit.GSXComponent")
	fmt.Fprintln(w, "import com.gosx.nativekit.rememberGSXSignal")
	fmt.Fprintln(w)
	for i, c := range mod.Components {
		if i > 0 {
			fmt.Fprintln(w)
		}
		if err := emitComponent(w, c); err != nil {
			return err
		}
	}
	return nil
}

func emitComponent(w io.Writer, c *nir.Component) error {
	if c.Props != nil {
		fmt.Fprintf(w, "data class %sProps(\n", c.Name)
		for i, f := range c.Props.Fields {
			sep := ","
			if i == len(c.Props.Fields)-1 {
				sep = ""
			}
			fmt.Fprintf(w, "    val %s: %s%s\n", f.Name, kotlinType(f.Type), sep)
		}
		fmt.Fprintln(w, ")")
		fmt.Fprintln(w)
	}
	fmt.Fprintln(w, "@GSXComponent")
	fmt.Fprintln(w, "@Composable")
	fmt.Fprintf(w, "fun %s(props: %sProps) {\n", c.Name, c.Name)
	for _, sig := range c.Signals {
		fmt.Fprintf(w, "    var %s by rememberGSXSignal(%s)\n", sig.Name, emitRxExpr(sig.Init))
	}
	if len(c.Signals) > 0 {
		fmt.Fprintln(w)
	}
	fmt.Fprintf(w, "%s\n", emitView(c.Body, 1))
	fmt.Fprintln(w, "}")
	return nil
}

func emitView(v nir.View, indent int) string {
	pad := strings.Repeat("    ", indent)
	switch n := v.(type) {
	case *nir.Element:
		if n.Tag == "text" {
			return pad + emitTextElement(n)
		}
		for _, h := range n.Handlers {
			if h.Event == "tap" {
				var sb strings.Builder
				sb.WriteString(pad)
				sb.WriteString("Button(onClick = { ")
				sb.WriteString(emitRxBlock(h.Body))
				sb.WriteString(" }) {\n")
				sb.WriteString(strings.Repeat("    ", indent+1))
				sb.WriteString("Text(text = ")
				sb.WriteString(kotlinQuote(emitChildrenInline(n.Children)))
				sb.WriteString(")\n")
				sb.WriteString(pad)
				sb.WriteString("}")
				return sb.String()
			}
		}
		tag := shared.ComposeTag(n.Tag)
		if tag == "" {
			return pad + "/* unsupported tag: " + n.Tag + " */"
		}
		var sb strings.Builder
		sb.WriteString(pad)
		sb.WriteString(tag)
		sb.WriteString(" {\n")
		for _, child := range n.Children {
			sb.WriteString(emitView(child, indent+1))
			sb.WriteByte('\n')
		}
		sb.WriteString(pad)
		sb.WriteString("}")
		return sb.String()
	case *nir.Text:
		return pad + "Text(text = " + kotlinQuote(n.Value) + ")"
	case *nir.ExprHole:
		return pad + `Text(text = "${` + emitRxExpr(&n.Expr) + `}")`
	default:
		return pad + "/* unsupported view */"
	}
}

func emitTextElement(n *nir.Element) string {
	if len(n.Children) == 0 {
		return `Text(text = "")`
	}
	if len(n.Children) == 1 {
		switch child := n.Children[0].(type) {
		case *nir.Text:
			return "Text(text = " + kotlinQuote(child.Value) + ")"
		case *nir.ExprHole:
			return `Text(text = "${` + emitRxExpr(&child.Expr) + `}")`
		}
	}
	return "Text(text = " + kotlinQuote(emitChildrenInline(n.Children)) + ")"
}

func emitChildrenInline(children []nir.View) string {
	var sb strings.Builder
	for _, child := range children {
		switch n := child.(type) {
		case *nir.Text:
			sb.WriteString(n.Value)
		case *nir.ExprHole:
			sb.WriteString("${")
			sb.WriteString(emitRxExpr(&n.Expr))
			sb.WriteString("}")
		}
	}
	return sb.String()
}

func emitRxExpr(e *nir.RxExpr) string {
	if e == nil {
		return ""
	}
	switch e.Kind {
	case "literal":
		if e.Literal == nil {
			return ""
		}
		if e.Literal.Type == "string" {
			return kotlinQuote(e.Literal.Value)
		}
		return e.Literal.Value
	case "ref":
		return e.Ref
	case "binop":
		if e.BinOp == nil {
			return ""
		}
		return fmt.Sprintf("%s %s %s", emitRxExpr(&e.BinOp.Left), e.BinOp.Op, emitRxExpr(&e.BinOp.Right))
	case "call":
		if e.Call == nil {
			return ""
		}
		args := make([]string, len(e.Call.Args))
		for i := range e.Call.Args {
			args[i] = emitRxExpr(&e.Call.Args[i])
		}
		return fmt.Sprintf("%s(%s)", e.Call.Callee, strings.Join(args, ", "))
	default:
		return ""
	}
}

func emitRxBlock(b nir.RxBlock) string {
	parts := make([]string, 0, len(b.Stmts))
	for _, s := range b.Stmts {
		switch s.Kind {
		case "expr":
			parts = append(parts, emitRxExpr(s.Expr))
		case "signal_set":
			parts = append(parts, fmt.Sprintf("%s = %s", s.Target, emitRxExpr(s.Value)))
		}
	}
	return strings.Join(parts, "; ")
}

func kotlinType(swiftType string) string {
	switch swiftType {
	case "Bool":
		return "Boolean"
	case "String", "Int", "Double", "Float":
		return swiftType
	default:
		return swiftType
	}
}

func kotlinQuote(s string) string {
	return strconv.Quote(s)
}
