// Code generated by gsxnative. DO NOT EDIT.
import GSXNativeKit
import SwiftUI

public struct Derived: GSXComponent {
    public struct Props {
        public var start: Int
    }
    public let props: Props
    @GSXSignal private var count: Int
    private var doubled: Int { count * 2 }

    public init(props: Props) {
        self.props = props
        self._count = GSXSignal(wrappedValue: props.start)
    }

    public var body: some View {
        VStack {
            Text("\(doubled)")
            Button("+") { count = count + 1 }
        }
    }
}
