// Code generated by gsxnative. DO NOT EDIT.
import GSXNativeKit
import SwiftUI

public struct Expressions: GSXComponent {
    public struct Props {
        public var title: String
        public var count: Int
        public var price: String
        public var tags: [String]
    }
    public let props: Props
    @GSXSignal private var title: String
    @GSXSignal private var count: Int
    @GSXSignal private var status: String
    private var normalized: String { title.trimmingCharacters(in: .whitespacesAndNewlines).replacingOccurrences(of: " ", with: "-").lowercased() }
    private var countText: String { String(count) }
    private var adjustedCount: Int { (Int(countText) ?? 0) + 2 }
    private var price: Double { (Double(props.price) ?? 0) }
    private var tagLine: String { props.tags.joined(separator: ",") }
    private var hasGo: Bool { title.hasPrefix("Go") }
    private var hasSX: Bool { title.contains("SX") }
    private var tagCount: Int { props.tags.count }

    public init(props: Props) {
        self.props = props
        self._title = GSXSignal(wrappedValue: props.title)
        self._count = GSXSignal(wrappedValue: props.count)
        self._status = GSXSignal(wrappedValue: "")
    }

    public var body: some View {
        VStack {
            Button("Refresh") { status = (count > 0 ? title.trimmingCharacters(in: .whitespacesAndNewlines).uppercased() : normalized) }
            Text("\(status)")
            Text("\(normalized)")
            Text("\(countText)")
            Text("\(adjustedCount)")
            Text("\(price)")
            Text("\(tagLine)")
            Text("\(hasGo)")
            Text("\(hasSX)")
            Text("\(tagCount)")
        }
    }
}
