// Code generated by gsxnative. DO NOT EDIT.
import GSXNativeKit
import SwiftUI

public struct FormControls: GSXComponent {
    public struct Props {
        public var bio: String
        public var enabled: Bool
        public var selectedIndex: Int
    }
    public let props: Props
    @GSXSignal private var bio: String
    @GSXSignal private var enabled: Bool
    @GSXSignal private var lastKey: String
    @GSXSignal private var choice: Int

    public init(props: Props) {
        self.props = props
        self._bio = GSXSignal(wrappedValue: props.bio)
        self._enabled = GSXSignal(wrappedValue: props.enabled)
        self._lastKey = GSXSignal(wrappedValue: "")
        self._choice = GSXSignal(wrappedValue: props.selectedIndex)
    }

    public var body: some View {
        VStack {
            TextEditor(text: Binding(get: { bio }, set: { eventValue in bio = eventValue }))
            Toggle("", isOn: Binding(get: { enabled }, set: { eventChecked in enabled = eventChecked }))
            TextField("Press key", text: .constant(lastKey)).onSubmit { let eventKey = "Enter"; lastKey = eventKey }
            Picker("", selection: Binding(get: { choice }, set: { eventSelectedIndex in choice = eventSelectedIndex })) {
                Text("One").tag(0)
                Text("Two").tag(1)
            }
            Text("\(bio)")
            Text("\(enabled)")
            Text("\(lastKey)")
            Text("\(choice)")
        }
    }
}
