// Code generated by gsxnative. DO NOT EDIT.
import GSXNativeKit
import SwiftUI

public struct Greeter: GSXComponent {
    public struct Props {
        public var initialName: String
    }
    public let props: Props
    @GSXSignal private var name: String

    public init(props: Props) {
        self.props = props
        self._name = GSXSignal(wrappedValue: props.initialName)
    }

    public var body: some View {
        VStack {
            TextField("Name", text: Binding(get: { name }, set: { eventValue in name = eventValue }))
            Text("Hello,\(name)")
        }
    }
}
