// Code generated by gsxnative. DO NOT EDIT.
import GSXNativeKit
import SwiftUI

public struct Panel: GSXComponent {
    public struct Props {
        public var start: Int
        public var label: String
    }
    public let props: Props
    @GSXSignal private var count: Int
    @GSXSignal private var label: String

    public init(props: Props) {
        self.props = props
        self._count = GSXSignal(wrappedValue: props.start)
        self._label = GSXSignal(wrappedValue: props.label)
    }

    public var body: some View {
        VStack {
            Text("\(label)")
            HStack {
                Button("Reset") { count = props.start; label = props.label }
                Text("\(count)")
                Button("+") { count = count + 1 }
                Button("Go") { count = count + 1; label = "advanced" }
            }
        }
    }
}
