// Code generated by gsxnative. DO NOT EDIT.
import GSXNativeKit
import SwiftUI

public struct Badge: GSXComponent {
    public struct Props {
        public var label: String
    }
    public let props: Props

    public init(props: Props) {
        self.props = props
    }

    public var body: some View {
        Text("\(props.label)")
    }
}

public struct Profile: GSXComponent {
    public struct Props {
        public var name: String
    }
    public let props: Props

    public init(props: Props) {
        self.props = props
    }

    public var body: some View {
        VStack {
            Badge(props: Badge.Props(label: props.name))
        }
    }
}
