// Code generated by gsxnative. DO NOT EDIT.
import GSXNativeKit
import SwiftUI

public struct Roster: GSXComponent {
    public struct Props {
        public var items: [String]
    }
    public let props: Props

    public init(props: Props) {
        self.props = props
    }

    public var body: some View {
        VStack {
            ForEach(props.items, id: \.self) { item in
                Text("\(item)")
            }
        }
    }
}
