// Code generated by gsxnative. DO NOT EDIT.
import GSXNativeKit
import SwiftUI

public struct Toggle: GSXComponent {
    public struct Props {
        public var initiallyVisible: Bool
    }
    public let props: Props
    @GSXSignal private var visible: Bool

    public init(props: Props) {
        self.props = props
        self._visible = GSXSignal(wrappedValue: props.initiallyVisible)
    }

    public var body: some View {
        VStack {
            if visible {
                Text("Visible")
            }
            Button("Hide") { visible = false }
        }
    }
}
