package ios

import (
	"fmt"
	"io"
	"strconv"
	"strings"

	"github.com/odvcencio/gosx-native/emit/shared"
	"github.com/odvcencio/gosx-native/target"
	"github.com/odvcencio/gosx/nir"
)

// Emit writes SwiftUI source for every component in mod.
func Emit(mod *nir.Module, w io.Writer) error {
	if err := target.Validate(mod, target.IOS); err != nil {
		return err
	}
	fmt.Fprintln(w, "// Code generated by gsxnative. DO NOT EDIT.")
	fmt.Fprintln(w, "import GSXNativeKit")
	fmt.Fprintln(w, "import SwiftUI")
	fmt.Fprintln(w)
	for i, c := range mod.Components {
		if i > 0 {
			fmt.Fprintln(w)
		}
		if err := emitComponent(w, c); err != nil {
			return err
		}
	}
	return nil
}

func emitComponent(w io.Writer, c *nir.Component) error {
	fmt.Fprintf(w, "public struct %s: GSXComponent {\n", c.Name)
	if c.Props != nil {
		fmt.Fprintln(w, "    public struct Props {")
		for _, f := range c.Props.Fields {
			fmt.Fprintf(w, "        public var %s: %s\n", f.Name, f.Type)
		}
		fmt.Fprintln(w, "    }")
		fmt.Fprintln(w, "    public let props: Props")
	}
	for _, sig := range c.Signals {
		fmt.Fprintf(w, "    @GSXSignal private var %s: %s\n", sig.Name, sig.Type)
	}
	for _, computed := range c.Computeds {
		fmt.Fprintf(w, "    private var %s: %s { %s }\n", computed.Name, computed.Type, emitRxExpr(computed.Body))
	}
	fmt.Fprintln(w)
	fmt.Fprintln(w, "    public init(props: Props) {")
	fmt.Fprintln(w, "        self.props = props")
	for _, sig := range c.Signals {
		fmt.Fprintf(w, "        self._%s = GSXSignal(wrappedValue: %s)\n", sig.Name, emitRxExpr(sig.Init))
	}
	fmt.Fprintln(w, "    }")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "    public var body: some View {")
	fmt.Fprintf(w, "%s\n", emitView(c.Body, 2))
	fmt.Fprintln(w, "    }")
	fmt.Fprintln(w, "}")
	return nil
}

func emitView(v nir.View, indent int) string {
	pad := strings.Repeat("    ", indent)
	switch n := v.(type) {
	case *nir.Element:
		if n.Tag == "scene3d" {
			return emitScene3D(n, indent)
		}
		if n.Tag == "text" {
			return pad + emitTextElement(n)
		}
		if n.Tag == "textinput" {
			return pad + emitTextInput(n)
		}
		if n.Tag == "textarea" {
			return pad + emitTextArea(n)
		}
		if n.Tag == "checkbox" {
			return pad + emitCheckbox(n)
		}
		if n.Tag == "select" {
			return emitSelect(n, indent)
		}
		for _, h := range n.Handlers {
			if h.Event == "tap" {
				return pad + fmt.Sprintf("Button(%s) { %s }", strconv.Quote(emitChildrenInline(n.Children)), emitRxBlock(h.Body))
			}
		}
		tag := shared.SwiftUITag(n.Tag)
		if tag == "" {
			return pad + "/* unsupported tag: " + n.Tag + " */"
		}
		var sb strings.Builder
		sb.WriteString(pad)
		sb.WriteString(tag)
		sb.WriteString(" {\n")
		for _, child := range n.Children {
			sb.WriteString(emitView(child, indent+1))
			sb.WriteByte('\n')
		}
		sb.WriteString(pad)
		sb.WriteString("}")
		return sb.String()
	case *nir.Text:
		return pad + fmt.Sprintf("Text(%s)", strconv.Quote(n.Value))
	case *nir.ExprHole:
		return pad + fmt.Sprintf(`Text("\(%s)")`, emitRxExpr(&n.Expr))
	case *nir.Conditional:
		return emitConditional(n, indent)
	case *nir.ComponentRef:
		return pad + emitComponentRef(n)
	case *nir.Loop:
		return emitLoop(n, indent)
	default:
		return pad + "/* unsupported view */"
	}
}

func emitScene3D(n *nir.Element, indent int) string {
	pad := strings.Repeat("    ", indent)
	childPad := strings.Repeat("    ", indent+1)
	grandchildPad := strings.Repeat("    ", indent+2)
	nodes := scene3DNodes(n)
	postEffects := scene3DPostEffects(n)
	htmlOverlays := scene3DHTMLOverlays(n)

	var sb strings.Builder
	sb.WriteString(pad)
	sb.WriteString("GSXScene3DView(scene: GSXScene3DScene(\n")
	sb.WriteString(childPad)
	sb.WriteString("width: ")
	sb.WriteString(scene3DDoubleAttr(n, "width", "640"))
	sb.WriteString(",\n")
	sb.WriteString(childPad)
	sb.WriteString("height: ")
	sb.WriteString(scene3DDoubleAttr(n, "height", "360"))
	sb.WriteString(",\n")
	sb.WriteString(childPad)
	sb.WriteString("background: ")
	sb.WriteString(scene3DStringAttr(n, "background", "#101820"))
	if len(postEffects) > 0 {
		sb.WriteString(",\n")
		sb.WriteString(childPad)
		sb.WriteString("postEffects: [\n")
		for i, effect := range postEffects {
			if i > 0 {
				sb.WriteString(",\n")
			}
			sb.WriteString(grandchildPad)
			sb.WriteString(emitScene3DPostEffect(effect))
		}
		sb.WriteByte('\n')
		sb.WriteString(childPad)
		sb.WriteString("]")
	}
	if len(htmlOverlays) > 0 {
		sb.WriteString(",\n")
		sb.WriteString(childPad)
		sb.WriteString("htmlOverlays: [\n")
		for i, overlay := range htmlOverlays {
			if i > 0 {
				sb.WriteString(",\n")
			}
			sb.WriteString(grandchildPad)
			sb.WriteString(emitScene3DHTMLOverlay(overlay, i))
		}
		sb.WriteByte('\n')
		sb.WriteString(childPad)
		sb.WriteString("]")
	}
	sb.WriteString(",\n")
	sb.WriteString(childPad)
	sb.WriteString("nodes: [\n")
	for i, node := range nodes {
		if i > 0 {
			sb.WriteString(",\n")
		}
		sb.WriteString(grandchildPad)
		sb.WriteString(emitScene3DNode(node, i))
	}
	if len(nodes) > 0 {
		sb.WriteByte('\n')
	}
	sb.WriteString(childPad)
	sb.WriteString("]\n")
	sb.WriteString(pad)
	sb.WriteString("))")
	return sb.String()
}

type scene3DNode struct {
	Tag   string
	Attrs []nir.Attr
}

type scene3DPostEffect struct {
	Tag   string
	Attrs []nir.Attr
}

type scene3DHTMLOverlay struct {
	Tag   string
	Attrs []nir.Attr
}

func emitScene3DNode(n scene3DNode, index int) string {
	id := scene3DStringAttrFromAttrs(n.Attrs, "id", fmt.Sprintf("%s-%d", n.Tag, index))
	return fmt.Sprintf(
		"GSXScene3DNode(id: %s, tag: %s, kind: %s, color: %s, x: %s, y: %s, z: %s, width: %s, height: %s, depth: %s, count: %s, size: %s)",
		id,
		strconv.Quote(n.Tag),
		scene3DStringAttrFromAttrs(n.Attrs, "kind", ""),
		scene3DStringAttrFromAttrs(n.Attrs, "color", "#8de1ff"),
		scene3DDoubleAttrFromAttrs(n.Attrs, "x", "0"),
		scene3DDoubleAttrFromAttrs(n.Attrs, "y", "0"),
		scene3DDoubleAttrFromAttrs(n.Attrs, "z", "0"),
		scene3DDoubleAttrFromAttrs(n.Attrs, "width", "1"),
		scene3DDoubleAttrFromAttrs(n.Attrs, "height", "1"),
		scene3DDoubleAttrFromAttrs(n.Attrs, "depth", "1"),
		scene3DIntAttrFromAttrs(n.Attrs, "count", "0"),
		scene3DDoubleAttrFromAttrs(n.Attrs, "size", "0"),
	)
}

func emitScene3DHTMLOverlay(overlay scene3DHTMLOverlay, index int) string {
	id := scene3DStringAttrFromAttrs(overlay.Attrs, "id", fmt.Sprintf("html-%d", index))
	return fmt.Sprintf(
		"GSXScene3DHTMLOverlay(id: %s, html: %s, className: %s, x: %s, y: %s, z: %s, width: %s, height: %s, opacity: %s, offsetX: %s, offsetY: %s, pointerEvents: %s)",
		id,
		scene3DHTMLMarkupAttrFromAttrs(overlay.Attrs),
		scene3DStringAttrFromAttrsAny(overlay.Attrs, "", "className", "class"),
		scene3DDoubleAttrFromAttrs(overlay.Attrs, "x", "0"),
		scene3DDoubleAttrFromAttrs(overlay.Attrs, "y", "0"),
		scene3DDoubleAttrFromAttrs(overlay.Attrs, "z", "0"),
		scene3DDoubleAttrFromAttrs(overlay.Attrs, "width", "1.8"),
		scene3DDoubleAttrFromAttrs(overlay.Attrs, "height", "0.72"),
		scene3DDoubleAttrFromAttrs(overlay.Attrs, "opacity", "1"),
		scene3DDoubleAttrFromAttrs(overlay.Attrs, "offsetX", "0"),
		scene3DDoubleAttrFromAttrs(overlay.Attrs, "offsetY", "0"),
		scene3DStringAttrFromAttrs(overlay.Attrs, "pointerEvents", "none"),
	)
}

func emitScene3DPostEffect(effect scene3DPostEffect) string {
	return fmt.Sprintf(
		"GSXScene3DPostEffect(kind: %s, threshold: %s, intensity: %s, radius: %s, scale: %s, saturation: %s, contrast: %s, exposure: %s, mode: %s, focusDistance: %s, aperture: %s, maxBlur: %s)",
		strconv.Quote(scene3DPostEffectKind(effect.Tag)),
		scene3DDoubleAttrFromAttrs(effect.Attrs, "threshold", "0"),
		scene3DDoubleAttrFromAttrs(effect.Attrs, "intensity", "0"),
		scene3DDoubleAttrFromAttrs(effect.Attrs, "radius", "0"),
		scene3DDoubleAttrFromAttrs(effect.Attrs, "scale", "0"),
		scene3DDoubleAttrFromAttrs(effect.Attrs, "saturation", "0"),
		scene3DDoubleAttrFromAttrs(effect.Attrs, "contrast", "0"),
		scene3DDoubleAttrFromAttrs(effect.Attrs, "exposure", "0"),
		scene3DStringAttrFromAttrs(effect.Attrs, "mode", ""),
		scene3DDoubleAttrFromAttrs(effect.Attrs, "focusDistance", "0"),
		scene3DDoubleAttrFromAttrs(effect.Attrs, "aperture", "0"),
		scene3DDoubleAttrFromAttrs(effect.Attrs, "maxBlur", "0"),
	)
}

func scene3DNodes(n *nir.Element) []scene3DNode {
	if n.Scene3D != nil {
		nodes := make([]scene3DNode, 0, len(n.Scene3D.Items))
		for _, item := range n.Scene3D.Items {
			if scene3DRenderableNode(item.Tag) {
				nodes = append(nodes, scene3DNode{Tag: item.Tag, Attrs: item.Attrs})
			}
		}
		return nodes
	}
	nodes := make([]scene3DNode, 0, len(n.Children))
	for _, child := range n.Children {
		element, ok := child.(*nir.Element)
		if !ok {
			continue
		}
		if scene3DRenderableNode(element.Tag) {
			nodes = append(nodes, scene3DNode{Tag: element.Tag, Attrs: element.Attrs})
		}
	}
	return nodes
}

func scene3DPostEffects(n *nir.Element) []scene3DPostEffect {
	if n.Scene3D != nil {
		effects := make([]scene3DPostEffect, 0, len(n.Scene3D.Items))
		for _, item := range n.Scene3D.Items {
			if scene3DPostEffectKind(item.Tag) != "" {
				effects = append(effects, scene3DPostEffect{Tag: item.Tag, Attrs: item.Attrs})
			}
		}
		return effects
	}
	effects := make([]scene3DPostEffect, 0, len(n.Children))
	for _, child := range n.Children {
		element, ok := child.(*nir.Element)
		if !ok {
			continue
		}
		if scene3DPostEffectKind(element.Tag) != "" {
			effects = append(effects, scene3DPostEffect{Tag: element.Tag, Attrs: element.Attrs})
		}
	}
	return effects
}

func scene3DHTMLOverlays(n *nir.Element) []scene3DHTMLOverlay {
	if n.Scene3D != nil {
		overlays := make([]scene3DHTMLOverlay, 0, len(n.Scene3D.Items))
		for _, item := range n.Scene3D.Items {
			if scene3DHTMLTag(item.Tag) {
				overlays = append(overlays, scene3DHTMLOverlay{Tag: item.Tag, Attrs: item.Attrs})
			}
		}
		return overlays
	}
	overlays := make([]scene3DHTMLOverlay, 0, len(n.Children))
	for _, child := range n.Children {
		element, ok := child.(*nir.Element)
		if !ok {
			continue
		}
		if scene3DHTMLTag(element.Tag) {
			overlays = append(overlays, scene3DHTMLOverlay{Tag: element.Tag, Attrs: element.Attrs})
		}
	}
	return overlays
}

func scene3DRenderableNode(tag string) bool {
	switch tag {
	case "mesh", "model", "points", "instancedMesh", "computeParticles":
		return true
	default:
		return false
	}
}

func scene3DHTMLTag(tag string) bool {
	return strings.EqualFold(strings.TrimSpace(tag), "html")
}

func scene3DPostEffectKind(tag string) string {
	switch strings.ToLower(strings.TrimSpace(tag)) {
	case "postfx.bloom":
		return "bloom"
	case "postfx.vignette":
		return "vignette"
	case "postfx.colorgrading":
		return "colorGrade"
	case "postfx.tonemap":
		return "toneMapping"
	default:
		return ""
	}
}

func emitComponentRef(n *nir.ComponentRef) string {
	props := make([]string, len(n.Props))
	for i := range n.Props {
		props[i] = fmt.Sprintf("%s: %s", n.Props[i].Name, emitRxExpr(&n.Props[i].Value))
	}
	return fmt.Sprintf("%s(props: %s.Props(%s))", n.Name, n.Name, strings.Join(props, ", "))
}

func emitLoop(n *nir.Loop, indent int) string {
	pad := strings.Repeat("    ", indent)
	itemName := n.ItemName
	if itemName == "" {
		itemName = "item"
	}
	var sb strings.Builder
	sb.WriteString(pad)
	sb.WriteString("ForEach(")
	sb.WriteString(emitRxExpr(&n.Items))
	sb.WriteString(", id: \\.self) { ")
	sb.WriteString(itemName)
	sb.WriteString(" in\n")
	for _, child := range n.Body {
		sb.WriteString(emitView(child, indent+1))
		sb.WriteByte('\n')
	}
	sb.WriteString(pad)
	sb.WriteString("}")
	return sb.String()
}

func emitConditional(n *nir.Conditional, indent int) string {
	pad := strings.Repeat("    ", indent)
	var sb strings.Builder
	sb.WriteString(pad)
	sb.WriteString("if ")
	sb.WriteString(emitRxExpr(&n.Condition))
	sb.WriteString(" {\n")
	for _, child := range n.Then {
		sb.WriteString(emitView(child, indent+1))
		sb.WriteByte('\n')
	}
	if len(n.Else) > 0 {
		sb.WriteString(pad)
		sb.WriteString("} else {\n")
		for _, child := range n.Else {
			sb.WriteString(emitView(child, indent+1))
			sb.WriteByte('\n')
		}
	}
	sb.WriteString(pad)
	sb.WriteString("}")
	return sb.String()
}

func emitTextInput(n *nir.Element) string {
	placeholder := literalAttr(n, "placeholder")
	value := attrExpr(n, "value")
	if value == nil {
		value = &nir.RxExpr{Kind: "literal", Literal: &nir.Literal{Type: "string", Value: ""}}
	}
	var out string
	for _, h := range n.Handlers {
		if h.Event == "input" || h.Event == "change" {
			out = fmt.Sprintf(
				"TextField(%s, text: Binding(get: { %s }, set: { eventValue in %s }))",
				strconv.Quote(placeholder),
				emitRxExpr(value),
				emitRxBlockWithEventBindings(h.Body, eventBindings{"value": "eventValue"}),
			)
			break
		}
	}
	if out == "" {
		out = fmt.Sprintf("TextField(%s, text: .constant(%s))", strconv.Quote(placeholder), emitRxExpr(value))
	}
	if keyHandler := handlerForEvent(n, "key"); keyHandler != nil {
		out += fmt.Sprintf(
			".onSubmit { let eventKey = %s; %s }",
			strconv.Quote("Enter"),
			emitRxBlockWithEventBindings(keyHandler.Body, eventBindings{"key": "eventKey"}),
		)
	}
	return out
}

func emitTextArea(n *nir.Element) string {
	value := attrExpr(n, "value")
	if value == nil {
		value = &nir.RxExpr{Kind: "literal", Literal: &nir.Literal{Type: "string", Value: ""}}
	}
	for _, h := range n.Handlers {
		if h.Event == "input" || h.Event == "change" {
			return fmt.Sprintf(
				"TextEditor(text: Binding(get: { %s }, set: { eventValue in %s }))",
				emitRxExpr(value),
				emitRxBlockWithEventBindings(h.Body, eventBindings{"value": "eventValue"}),
			)
		}
	}
	return fmt.Sprintf("TextEditor(text: .constant(%s))", emitRxExpr(value))
}

func emitCheckbox(n *nir.Element) string {
	checked := attrExpr(n, "checked")
	if checked == nil {
		checked = &nir.RxExpr{Kind: "literal", Literal: &nir.Literal{Type: "bool", Value: "false"}}
	}
	for _, h := range n.Handlers {
		if h.Event == "change" || h.Event == "input" {
			return fmt.Sprintf(
				"Toggle(\"\", isOn: Binding(get: { %s }, set: { eventChecked in %s }))",
				emitRxExpr(checked),
				emitRxBlockWithEventBindings(h.Body, eventBindings{"checked": "eventChecked"}),
			)
		}
	}
	return fmt.Sprintf("Toggle(\"\", isOn: .constant(%s))", emitRxExpr(checked))
}

func emitSelect(n *nir.Element, indent int) string {
	pad := strings.Repeat("    ", indent)
	childPad := strings.Repeat("    ", indent+1)
	selection := attrExpr(n, "selectedIndex")
	if selection == nil {
		selection = &nir.RxExpr{Kind: "literal", Literal: &nir.Literal{Type: "int", Value: "0"}}
	}
	binding := fmt.Sprintf(".constant(%s)", emitRxExpr(selection))
	if handler := handlerForEvent(n, "change"); handler != nil {
		binding = fmt.Sprintf(
			"Binding(get: { %s }, set: { eventSelectedIndex in %s })",
			emitRxExpr(selection),
			emitRxBlockWithEventBindings(handler.Body, eventBindings{"selectedIndex": "eventSelectedIndex"}),
		)
	}
	var sb strings.Builder
	sb.WriteString(pad)
	sb.WriteString("Picker(\"\", selection: ")
	sb.WriteString(binding)
	sb.WriteString(") {\n")
	for index, label := range optionLabels(n.Children) {
		sb.WriteString(childPad)
		sb.WriteString("Text(")
		sb.WriteString(strconv.Quote(label))
		sb.WriteString(").tag(")
		sb.WriteString(strconv.Itoa(index))
		sb.WriteString(")\n")
	}
	sb.WriteString(pad)
	sb.WriteString("}")
	return sb.String()
}

func emitTextElement(n *nir.Element) string {
	if len(n.Children) == 0 {
		return `Text("")`
	}
	if len(n.Children) == 1 {
		switch child := n.Children[0].(type) {
		case *nir.Text:
			return fmt.Sprintf("Text(%s)", strconv.Quote(child.Value))
		case *nir.ExprHole:
			return fmt.Sprintf(`Text("\(%s)")`, emitRxExpr(&child.Expr))
		}
	}
	return fmt.Sprintf("Text(%s)", emitInterpolatedString(n.Children))
}

func emitChildrenInline(children []nir.View) string {
	var sb strings.Builder
	for _, child := range children {
		switch n := child.(type) {
		case *nir.Text:
			sb.WriteString(n.Value)
		case *nir.ExprHole:
			sb.WriteString(`\(`)
			sb.WriteString(emitRxExpr(&n.Expr))
			sb.WriteString(")")
		}
	}
	return sb.String()
}

func emitInterpolatedString(children []nir.View) string {
	var sb strings.Builder
	sb.WriteByte('"')
	for _, child := range children {
		switch n := child.(type) {
		case *nir.Text:
			sb.WriteString(quotedStringBody(n.Value))
		case *nir.ExprHole:
			sb.WriteString(`\(`)
			sb.WriteString(emitRxExpr(&n.Expr))
			sb.WriteString(")")
		}
	}
	sb.WriteByte('"')
	return sb.String()
}

func handlerForEvent(n *nir.Element, event string) *nir.Handler {
	for i := range n.Handlers {
		if n.Handlers[i].Event == event {
			return &n.Handlers[i]
		}
	}
	return nil
}

func optionLabels(children []nir.View) []string {
	labels := make([]string, 0, len(children))
	for _, child := range children {
		option, ok := child.(*nir.Element)
		if !ok || option.Tag != "option" {
			continue
		}
		labels = append(labels, emitChildrenInline(option.Children))
	}
	return labels
}

func quotedStringBody(s string) string {
	quoted := strconv.Quote(s)
	return quoted[1 : len(quoted)-1]
}

type eventBindings map[string]string

func (b eventBindings) ref(ref string) (string, bool) {
	if !strings.HasPrefix(ref, "event.") {
		return "", false
	}
	value := b[strings.TrimPrefix(ref, "event.")]
	return value, value != ""
}

func emitRxExpr(e *nir.RxExpr) string {
	return emitRxExprWithEventBindings(e, nil)
}

func emitRxExprWithEventBindings(e *nir.RxExpr, bindings eventBindings) string {
	if e == nil {
		return ""
	}
	switch e.Kind {
	case "literal":
		if e.Literal == nil {
			return ""
		}
		if e.Literal.Type == "string" {
			return strconv.Quote(e.Literal.Value)
		}
		return e.Literal.Value
	case "ref":
		if value, ok := bindings.ref(e.Ref); ok {
			return value
		}
		return e.Ref
	case "binop":
		if e.BinOp == nil {
			return ""
		}
		return fmt.Sprintf("%s %s %s", emitRxExprWithEventBindings(&e.BinOp.Left, bindings), e.BinOp.Op, emitRxExprWithEventBindings(&e.BinOp.Right, bindings))
	case "cond":
		if e.Cond == nil {
			return ""
		}
		return fmt.Sprintf(
			"(%s ? %s : %s)",
			emitRxExprWithEventBindings(&e.Cond.Condition, bindings),
			emitRxExprWithEventBindings(&e.Cond.Then, bindings),
			emitRxExprWithEventBindings(&e.Cond.Else, bindings),
		)
	case "call":
		if e.Call == nil {
			return ""
		}
		return emitCall(e.Call, bindings)
	default:
		return ""
	}
}

func emitCall(c *nir.Call, bindings eventBindings) string {
	args := make([]string, len(c.Args))
	for i := range c.Args {
		args[i] = emitRxExprWithEventBindings(&c.Args[i], bindings)
	}
	if len(args) == 0 {
		return c.Callee + "()"
	}
	receiver := args[0]
	switch c.Callee {
	case "len":
		return receiver + ".count"
	case "upper":
		return receiver + ".uppercased()"
	case "lower":
		return receiver + ".lowercased()"
	case "trim":
		return receiver + ".trimmingCharacters(in: .whitespacesAndNewlines)"
	case "split":
		if len(args) != 2 {
			return receiver
		}
		return receiver + ".components(separatedBy: " + args[1] + ")"
	case "join":
		if len(args) != 2 {
			return receiver
		}
		return receiver + ".joined(separator: " + args[1] + ")"
	case "replace":
		if len(args) != 3 {
			return receiver
		}
		return receiver + ".replacingOccurrences(of: " + args[1] + ", with: " + args[2] + ")"
	case "substring":
		if len(args) != 3 {
			return receiver
		}
		return "String(" + receiver + ".dropFirst(" + args[1] + ").prefix(" + args[2] + " - " + args[1] + "))"
	case "startsWith":
		if len(args) != 2 {
			return receiver
		}
		return receiver + ".hasPrefix(" + args[1] + ")"
	case "endsWith":
		if len(args) != 2 {
			return receiver
		}
		return receiver + ".hasSuffix(" + args[1] + ")"
	case "contains":
		if len(args) != 2 {
			return receiver
		}
		return receiver + ".contains(" + args[1] + ")"
	case "toString":
		return "String(" + receiver + ")"
	case "toInt":
		return "(Int(" + receiver + ") ?? 0)"
	case "toFloat":
		return "(Double(" + receiver + ") ?? 0)"
	default:
		return fmt.Sprintf("%s(%s)", c.Callee, strings.Join(args, ", "))
	}
}

func emitRxBlock(b nir.RxBlock) string {
	return emitRxBlockWithEventBindings(b, nil)
}

func emitRxBlockWithEventBindings(b nir.RxBlock, bindings eventBindings) string {
	parts := make([]string, 0, len(b.Stmts))
	for _, s := range b.Stmts {
		switch s.Kind {
		case "expr":
			parts = append(parts, emitRxExprWithEventBindings(s.Expr, bindings))
		case "signal_set":
			parts = append(parts, fmt.Sprintf("%s = %s", s.Target, emitRxExprWithEventBindings(s.Value, bindings)))
		}
	}
	return strings.Join(parts, "; ")
}

func attrExpr(n *nir.Element, name string) *nir.RxExpr {
	return attrExprFromAttrs(n.Attrs, name)
}

func attrExprFromAttrs(attrs []nir.Attr, name string) *nir.RxExpr {
	for i := range attrs {
		if attrs[i].Name == name {
			return &attrs[i].Value
		}
	}
	return nil
}

func literalAttr(n *nir.Element, name string) string {
	expr := attrExpr(n, name)
	if expr == nil || expr.Kind != "literal" || expr.Literal == nil {
		return ""
	}
	return expr.Literal.Value
}

func scene3DStringAttr(n *nir.Element, name, fallback string) string {
	return scene3DStringAttrFromAttrs(n.Attrs, name, fallback)
}

func scene3DStringAttrFromAttrs(attrs []nir.Attr, name, fallback string) string {
	expr := attrExprFromAttrs(attrs, name)
	if expr == nil {
		return strconv.Quote(fallback)
	}
	return emitRxExpr(expr)
}

func scene3DStringAttrFromAttrsAny(attrs []nir.Attr, fallback string, names ...string) string {
	for _, name := range names {
		expr := attrExprFromAttrs(attrs, name)
		if expr != nil {
			return emitRxExpr(expr)
		}
	}
	return strconv.Quote(fallback)
}

func scene3DHTMLMarkupAttrFromAttrs(attrs []nir.Attr) string {
	return scene3DStringAttrFromAttrsAny(attrs, "", "html", "markup", "content")
}

func scene3DDoubleAttr(n *nir.Element, name, fallback string) string {
	return scene3DDoubleAttrFromAttrs(n.Attrs, name, fallback)
}

func scene3DDoubleAttrFromAttrs(attrs []nir.Attr, name, fallback string) string {
	expr := attrExprFromAttrs(attrs, name)
	if expr == nil {
		return fallback
	}
	if expr.Kind == "literal" && expr.Literal != nil {
		return expr.Literal.Value
	}
	return "Double(" + emitRxExpr(expr) + ")"
}

func scene3DIntAttr(n *nir.Element, name, fallback string) string {
	return scene3DIntAttrFromAttrs(n.Attrs, name, fallback)
}

func scene3DIntAttrFromAttrs(attrs []nir.Attr, name, fallback string) string {
	expr := attrExprFromAttrs(attrs, name)
	if expr == nil {
		return fallback
	}
	if expr.Kind == "literal" && expr.Literal != nil {
		return expr.Literal.Value
	}
	return emitRxExpr(expr)
}
