package ios

import (
	"fmt"
	"io"
	"strconv"
	"strings"

	"github.com/odvcencio/gosx-native/emit/shared"
	"github.com/odvcencio/gosx/nir"
)

// Emit writes SwiftUI source for every component in mod.
func Emit(mod *nir.Module, w io.Writer) error {
	fmt.Fprintln(w, "// Code generated by gsxnative. DO NOT EDIT.")
	fmt.Fprintln(w, "import GSXNativeKit")
	fmt.Fprintln(w, "import SwiftUI")
	fmt.Fprintln(w)
	for i, c := range mod.Components {
		if i > 0 {
			fmt.Fprintln(w)
		}
		if err := emitComponent(w, c); err != nil {
			return err
		}
	}
	return nil
}

func emitComponent(w io.Writer, c *nir.Component) error {
	fmt.Fprintf(w, "public struct %s: GSXComponent {\n", c.Name)
	if c.Props != nil {
		fmt.Fprintln(w, "    public struct Props {")
		for _, f := range c.Props.Fields {
			fmt.Fprintf(w, "        public var %s: %s\n", f.Name, f.Type)
		}
		fmt.Fprintln(w, "    }")
		fmt.Fprintln(w, "    public let props: Props")
	}
	for _, sig := range c.Signals {
		fmt.Fprintf(w, "    @GSXSignal private var %s: %s\n", sig.Name, sig.Type)
	}
	for _, computed := range c.Computeds {
		fmt.Fprintf(w, "    private var %s: %s { %s }\n", computed.Name, computed.Type, emitRxExpr(computed.Body))
	}
	fmt.Fprintln(w)
	fmt.Fprintln(w, "    public init(props: Props) {")
	fmt.Fprintln(w, "        self.props = props")
	for _, sig := range c.Signals {
		fmt.Fprintf(w, "        self._%s = GSXSignal(wrappedValue: %s)\n", sig.Name, emitRxExpr(sig.Init))
	}
	fmt.Fprintln(w, "    }")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "    public var body: some View {")
	fmt.Fprintf(w, "%s\n", emitView(c.Body, 2))
	fmt.Fprintln(w, "    }")
	fmt.Fprintln(w, "}")
	return nil
}

func emitView(v nir.View, indent int) string {
	pad := strings.Repeat("    ", indent)
	switch n := v.(type) {
	case *nir.Element:
		if n.Tag == "text" {
			return pad + emitTextElement(n)
		}
		if n.Tag == "textinput" {
			return pad + emitTextInput(n)
		}
		for _, h := range n.Handlers {
			if h.Event == "tap" {
				return pad + fmt.Sprintf("Button(%s) { %s }", strconv.Quote(emitChildrenInline(n.Children)), emitRxBlock(h.Body))
			}
		}
		tag := shared.SwiftUITag(n.Tag)
		if tag == "" {
			return pad + "/* unsupported tag: " + n.Tag + " */"
		}
		var sb strings.Builder
		sb.WriteString(pad)
		sb.WriteString(tag)
		sb.WriteString(" {\n")
		for _, child := range n.Children {
			sb.WriteString(emitView(child, indent+1))
			sb.WriteByte('\n')
		}
		sb.WriteString(pad)
		sb.WriteString("}")
		return sb.String()
	case *nir.Text:
		return pad + fmt.Sprintf("Text(%s)", strconv.Quote(n.Value))
	case *nir.ExprHole:
		return pad + fmt.Sprintf(`Text("\(%s)")`, emitRxExpr(&n.Expr))
	case *nir.Conditional:
		return emitConditional(n, indent)
	case *nir.ComponentRef:
		return pad + emitComponentRef(n)
	default:
		return pad + "/* unsupported view */"
	}
}

func emitComponentRef(n *nir.ComponentRef) string {
	props := make([]string, len(n.Props))
	for i := range n.Props {
		props[i] = fmt.Sprintf("%s: %s", n.Props[i].Name, emitRxExpr(&n.Props[i].Value))
	}
	return fmt.Sprintf("%s(props: %s.Props(%s))", n.Name, n.Name, strings.Join(props, ", "))
}

func emitConditional(n *nir.Conditional, indent int) string {
	pad := strings.Repeat("    ", indent)
	var sb strings.Builder
	sb.WriteString(pad)
	sb.WriteString("if ")
	sb.WriteString(emitRxExpr(&n.Condition))
	sb.WriteString(" {\n")
	for _, child := range n.Then {
		sb.WriteString(emitView(child, indent+1))
		sb.WriteByte('\n')
	}
	if len(n.Else) > 0 {
		sb.WriteString(pad)
		sb.WriteString("} else {\n")
		for _, child := range n.Else {
			sb.WriteString(emitView(child, indent+1))
			sb.WriteByte('\n')
		}
	}
	sb.WriteString(pad)
	sb.WriteString("}")
	return sb.String()
}

func emitTextInput(n *nir.Element) string {
	placeholder := literalAttr(n, "placeholder")
	value := attrExpr(n, "value")
	if value == nil {
		value = &nir.RxExpr{Kind: "literal", Literal: &nir.Literal{Type: "string", Value: ""}}
	}
	for _, h := range n.Handlers {
		if h.Event == "input" || h.Event == "change" {
			return fmt.Sprintf(
				"TextField(%s, text: Binding(get: { %s }, set: { eventValue in %s }))",
				strconv.Quote(placeholder),
				emitRxExpr(value),
				emitRxBlockWithEventValue(h.Body, "eventValue"),
			)
		}
	}
	return fmt.Sprintf("TextField(%s, text: .constant(%s))", strconv.Quote(placeholder), emitRxExpr(value))
}

func emitTextElement(n *nir.Element) string {
	if len(n.Children) == 0 {
		return `Text("")`
	}
	if len(n.Children) == 1 {
		switch child := n.Children[0].(type) {
		case *nir.Text:
			return fmt.Sprintf("Text(%s)", strconv.Quote(child.Value))
		case *nir.ExprHole:
			return fmt.Sprintf(`Text("\(%s)")`, emitRxExpr(&child.Expr))
		}
	}
	return fmt.Sprintf("Text(%s)", emitInterpolatedString(n.Children))
}

func emitChildrenInline(children []nir.View) string {
	var sb strings.Builder
	for _, child := range children {
		switch n := child.(type) {
		case *nir.Text:
			sb.WriteString(n.Value)
		case *nir.ExprHole:
			sb.WriteString(`\(`)
			sb.WriteString(emitRxExpr(&n.Expr))
			sb.WriteString(")")
		}
	}
	return sb.String()
}

func emitInterpolatedString(children []nir.View) string {
	var sb strings.Builder
	sb.WriteByte('"')
	for _, child := range children {
		switch n := child.(type) {
		case *nir.Text:
			sb.WriteString(quotedStringBody(n.Value))
		case *nir.ExprHole:
			sb.WriteString(`\(`)
			sb.WriteString(emitRxExpr(&n.Expr))
			sb.WriteString(")")
		}
	}
	sb.WriteByte('"')
	return sb.String()
}

func quotedStringBody(s string) string {
	quoted := strconv.Quote(s)
	return quoted[1 : len(quoted)-1]
}

func emitRxExpr(e *nir.RxExpr) string {
	return emitRxExprWithEventValue(e, "")
}

func emitRxExprWithEventValue(e *nir.RxExpr, eventValue string) string {
	if e == nil {
		return ""
	}
	switch e.Kind {
	case "literal":
		if e.Literal == nil {
			return ""
		}
		if e.Literal.Type == "string" {
			return strconv.Quote(e.Literal.Value)
		}
		return e.Literal.Value
	case "ref":
		if eventValue != "" && e.Ref == "event.value" {
			return eventValue
		}
		return e.Ref
	case "binop":
		if e.BinOp == nil {
			return ""
		}
		return fmt.Sprintf("%s %s %s", emitRxExprWithEventValue(&e.BinOp.Left, eventValue), e.BinOp.Op, emitRxExprWithEventValue(&e.BinOp.Right, eventValue))
	case "call":
		if e.Call == nil {
			return ""
		}
		args := make([]string, len(e.Call.Args))
		for i := range e.Call.Args {
			args[i] = emitRxExprWithEventValue(&e.Call.Args[i], eventValue)
		}
		return fmt.Sprintf("%s(%s)", e.Call.Callee, strings.Join(args, ", "))
	default:
		return ""
	}
}

func emitRxBlock(b nir.RxBlock) string {
	return emitRxBlockWithEventValue(b, "")
}

func emitRxBlockWithEventValue(b nir.RxBlock, eventValue string) string {
	parts := make([]string, 0, len(b.Stmts))
	for _, s := range b.Stmts {
		switch s.Kind {
		case "expr":
			parts = append(parts, emitRxExprWithEventValue(s.Expr, eventValue))
		case "signal_set":
			parts = append(parts, fmt.Sprintf("%s = %s", s.Target, emitRxExprWithEventValue(s.Value, eventValue)))
		}
	}
	return strings.Join(parts, "; ")
}

func attrExpr(n *nir.Element, name string) *nir.RxExpr {
	for i := range n.Attrs {
		if n.Attrs[i].Name == name {
			return &n.Attrs[i].Value
		}
	}
	return nil
}

func literalAttr(n *nir.Element, name string) string {
	expr := attrExpr(n, name)
	if expr == nil || expr.Kind != "literal" || expr.Literal == nil {
		return ""
	}
	return expr.Literal.Value
}
