package ios

import (
	"fmt"
	"io"
	"strconv"
	"strings"

	"github.com/odvcencio/gosx-native/emit/shared"
	"github.com/odvcencio/gosx/nir"
)

// Emit writes SwiftUI source for every component in mod.
func Emit(mod *nir.Module, w io.Writer) error {
	fmt.Fprintln(w, "// Code generated by gsxnative. DO NOT EDIT.")
	fmt.Fprintln(w, "import GSXNativeKit")
	fmt.Fprintln(w, "import SwiftUI")
	fmt.Fprintln(w)
	for i, c := range mod.Components {
		if i > 0 {
			fmt.Fprintln(w)
		}
		if err := emitComponent(w, c); err != nil {
			return err
		}
	}
	return nil
}

func emitComponent(w io.Writer, c *nir.Component) error {
	fmt.Fprintf(w, "public struct %s: GSXComponent {\n", c.Name)
	if c.Props != nil {
		fmt.Fprintln(w, "    public struct Props {")
		for _, f := range c.Props.Fields {
			fmt.Fprintf(w, "        public var %s: %s\n", f.Name, f.Type)
		}
		fmt.Fprintln(w, "    }")
		fmt.Fprintln(w, "    public let props: Props")
	}
	for _, sig := range c.Signals {
		fmt.Fprintf(w, "    @GSXSignal private var %s: %s\n", sig.Name, sig.Type)
	}
	for _, computed := range c.Computeds {
		fmt.Fprintf(w, "    private var %s: %s { %s }\n", computed.Name, computed.Type, emitRxExpr(computed.Body))
	}
	fmt.Fprintln(w)
	fmt.Fprintln(w, "    public init(props: Props) {")
	fmt.Fprintln(w, "        self.props = props")
	for _, sig := range c.Signals {
		fmt.Fprintf(w, "        self._%s = GSXSignal(wrappedValue: %s)\n", sig.Name, emitRxExpr(sig.Init))
	}
	fmt.Fprintln(w, "    }")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "    public var body: some View {")
	fmt.Fprintf(w, "%s\n", emitView(c.Body, 2))
	fmt.Fprintln(w, "    }")
	fmt.Fprintln(w, "}")
	return nil
}

func emitView(v nir.View, indent int) string {
	pad := strings.Repeat("    ", indent)
	switch n := v.(type) {
	case *nir.Element:
		if n.Tag == "text" {
			return pad + emitTextElement(n)
		}
		if n.Tag == "textinput" {
			return pad + emitTextInput(n)
		}
		if n.Tag == "textarea" {
			return pad + emitTextArea(n)
		}
		if n.Tag == "checkbox" {
			return pad + emitCheckbox(n)
		}
		if n.Tag == "select" {
			return emitSelect(n, indent)
		}
		for _, h := range n.Handlers {
			if h.Event == "tap" {
				return pad + fmt.Sprintf("Button(%s) { %s }", strconv.Quote(emitChildrenInline(n.Children)), emitRxBlock(h.Body))
			}
		}
		tag := shared.SwiftUITag(n.Tag)
		if tag == "" {
			return pad + "/* unsupported tag: " + n.Tag + " */"
		}
		var sb strings.Builder
		sb.WriteString(pad)
		sb.WriteString(tag)
		sb.WriteString(" {\n")
		for _, child := range n.Children {
			sb.WriteString(emitView(child, indent+1))
			sb.WriteByte('\n')
		}
		sb.WriteString(pad)
		sb.WriteString("}")
		return sb.String()
	case *nir.Text:
		return pad + fmt.Sprintf("Text(%s)", strconv.Quote(n.Value))
	case *nir.ExprHole:
		return pad + fmt.Sprintf(`Text("\(%s)")`, emitRxExpr(&n.Expr))
	case *nir.Conditional:
		return emitConditional(n, indent)
	case *nir.ComponentRef:
		return pad + emitComponentRef(n)
	case *nir.Loop:
		return emitLoop(n, indent)
	default:
		return pad + "/* unsupported view */"
	}
}

func emitComponentRef(n *nir.ComponentRef) string {
	props := make([]string, len(n.Props))
	for i := range n.Props {
		props[i] = fmt.Sprintf("%s: %s", n.Props[i].Name, emitRxExpr(&n.Props[i].Value))
	}
	return fmt.Sprintf("%s(props: %s.Props(%s))", n.Name, n.Name, strings.Join(props, ", "))
}

func emitLoop(n *nir.Loop, indent int) string {
	pad := strings.Repeat("    ", indent)
	itemName := n.ItemName
	if itemName == "" {
		itemName = "item"
	}
	var sb strings.Builder
	sb.WriteString(pad)
	sb.WriteString("ForEach(")
	sb.WriteString(emitRxExpr(&n.Items))
	sb.WriteString(", id: \\.self) { ")
	sb.WriteString(itemName)
	sb.WriteString(" in\n")
	for _, child := range n.Body {
		sb.WriteString(emitView(child, indent+1))
		sb.WriteByte('\n')
	}
	sb.WriteString(pad)
	sb.WriteString("}")
	return sb.String()
}

func emitConditional(n *nir.Conditional, indent int) string {
	pad := strings.Repeat("    ", indent)
	var sb strings.Builder
	sb.WriteString(pad)
	sb.WriteString("if ")
	sb.WriteString(emitRxExpr(&n.Condition))
	sb.WriteString(" {\n")
	for _, child := range n.Then {
		sb.WriteString(emitView(child, indent+1))
		sb.WriteByte('\n')
	}
	if len(n.Else) > 0 {
		sb.WriteString(pad)
		sb.WriteString("} else {\n")
		for _, child := range n.Else {
			sb.WriteString(emitView(child, indent+1))
			sb.WriteByte('\n')
		}
	}
	sb.WriteString(pad)
	sb.WriteString("}")
	return sb.String()
}

func emitTextInput(n *nir.Element) string {
	placeholder := literalAttr(n, "placeholder")
	value := attrExpr(n, "value")
	if value == nil {
		value = &nir.RxExpr{Kind: "literal", Literal: &nir.Literal{Type: "string", Value: ""}}
	}
	var out string
	for _, h := range n.Handlers {
		if h.Event == "input" || h.Event == "change" {
			out = fmt.Sprintf(
				"TextField(%s, text: Binding(get: { %s }, set: { eventValue in %s }))",
				strconv.Quote(placeholder),
				emitRxExpr(value),
				emitRxBlockWithEventBindings(h.Body, eventBindings{"value": "eventValue"}),
			)
			break
		}
	}
	if out == "" {
		out = fmt.Sprintf("TextField(%s, text: .constant(%s))", strconv.Quote(placeholder), emitRxExpr(value))
	}
	if keyHandler := handlerForEvent(n, "key"); keyHandler != nil {
		out += fmt.Sprintf(
			".onSubmit { let eventKey = %s; %s }",
			strconv.Quote("Enter"),
			emitRxBlockWithEventBindings(keyHandler.Body, eventBindings{"key": "eventKey"}),
		)
	}
	return out
}

func emitTextArea(n *nir.Element) string {
	value := attrExpr(n, "value")
	if value == nil {
		value = &nir.RxExpr{Kind: "literal", Literal: &nir.Literal{Type: "string", Value: ""}}
	}
	for _, h := range n.Handlers {
		if h.Event == "input" || h.Event == "change" {
			return fmt.Sprintf(
				"TextEditor(text: Binding(get: { %s }, set: { eventValue in %s }))",
				emitRxExpr(value),
				emitRxBlockWithEventBindings(h.Body, eventBindings{"value": "eventValue"}),
			)
		}
	}
	return fmt.Sprintf("TextEditor(text: .constant(%s))", emitRxExpr(value))
}

func emitCheckbox(n *nir.Element) string {
	checked := attrExpr(n, "checked")
	if checked == nil {
		checked = &nir.RxExpr{Kind: "literal", Literal: &nir.Literal{Type: "bool", Value: "false"}}
	}
	for _, h := range n.Handlers {
		if h.Event == "change" || h.Event == "input" {
			return fmt.Sprintf(
				"Toggle(\"\", isOn: Binding(get: { %s }, set: { eventChecked in %s }))",
				emitRxExpr(checked),
				emitRxBlockWithEventBindings(h.Body, eventBindings{"checked": "eventChecked"}),
			)
		}
	}
	return fmt.Sprintf("Toggle(\"\", isOn: .constant(%s))", emitRxExpr(checked))
}

func emitSelect(n *nir.Element, indent int) string {
	pad := strings.Repeat("    ", indent)
	childPad := strings.Repeat("    ", indent+1)
	selection := attrExpr(n, "selectedIndex")
	if selection == nil {
		selection = &nir.RxExpr{Kind: "literal", Literal: &nir.Literal{Type: "int", Value: "0"}}
	}
	binding := fmt.Sprintf(".constant(%s)", emitRxExpr(selection))
	if handler := handlerForEvent(n, "change"); handler != nil {
		binding = fmt.Sprintf(
			"Binding(get: { %s }, set: { eventSelectedIndex in %s })",
			emitRxExpr(selection),
			emitRxBlockWithEventBindings(handler.Body, eventBindings{"selectedIndex": "eventSelectedIndex"}),
		)
	}
	var sb strings.Builder
	sb.WriteString(pad)
	sb.WriteString("Picker(\"\", selection: ")
	sb.WriteString(binding)
	sb.WriteString(") {\n")
	for index, label := range optionLabels(n.Children) {
		sb.WriteString(childPad)
		sb.WriteString("Text(")
		sb.WriteString(strconv.Quote(label))
		sb.WriteString(").tag(")
		sb.WriteString(strconv.Itoa(index))
		sb.WriteString(")\n")
	}
	sb.WriteString(pad)
	sb.WriteString("}")
	return sb.String()
}

func emitTextElement(n *nir.Element) string {
	if len(n.Children) == 0 {
		return `Text("")`
	}
	if len(n.Children) == 1 {
		switch child := n.Children[0].(type) {
		case *nir.Text:
			return fmt.Sprintf("Text(%s)", strconv.Quote(child.Value))
		case *nir.ExprHole:
			return fmt.Sprintf(`Text("\(%s)")`, emitRxExpr(&child.Expr))
		}
	}
	return fmt.Sprintf("Text(%s)", emitInterpolatedString(n.Children))
}

func emitChildrenInline(children []nir.View) string {
	var sb strings.Builder
	for _, child := range children {
		switch n := child.(type) {
		case *nir.Text:
			sb.WriteString(n.Value)
		case *nir.ExprHole:
			sb.WriteString(`\(`)
			sb.WriteString(emitRxExpr(&n.Expr))
			sb.WriteString(")")
		}
	}
	return sb.String()
}

func emitInterpolatedString(children []nir.View) string {
	var sb strings.Builder
	sb.WriteByte('"')
	for _, child := range children {
		switch n := child.(type) {
		case *nir.Text:
			sb.WriteString(quotedStringBody(n.Value))
		case *nir.ExprHole:
			sb.WriteString(`\(`)
			sb.WriteString(emitRxExpr(&n.Expr))
			sb.WriteString(")")
		}
	}
	sb.WriteByte('"')
	return sb.String()
}

func handlerForEvent(n *nir.Element, event string) *nir.Handler {
	for i := range n.Handlers {
		if n.Handlers[i].Event == event {
			return &n.Handlers[i]
		}
	}
	return nil
}

func optionLabels(children []nir.View) []string {
	labels := make([]string, 0, len(children))
	for _, child := range children {
		option, ok := child.(*nir.Element)
		if !ok || option.Tag != "option" {
			continue
		}
		labels = append(labels, emitChildrenInline(option.Children))
	}
	return labels
}

func quotedStringBody(s string) string {
	quoted := strconv.Quote(s)
	return quoted[1 : len(quoted)-1]
}

type eventBindings map[string]string

func (b eventBindings) ref(ref string) (string, bool) {
	if !strings.HasPrefix(ref, "event.") {
		return "", false
	}
	value := b[strings.TrimPrefix(ref, "event.")]
	return value, value != ""
}

func emitRxExpr(e *nir.RxExpr) string {
	return emitRxExprWithEventBindings(e, nil)
}

func emitRxExprWithEventBindings(e *nir.RxExpr, bindings eventBindings) string {
	if e == nil {
		return ""
	}
	switch e.Kind {
	case "literal":
		if e.Literal == nil {
			return ""
		}
		if e.Literal.Type == "string" {
			return strconv.Quote(e.Literal.Value)
		}
		return e.Literal.Value
	case "ref":
		if value, ok := bindings.ref(e.Ref); ok {
			return value
		}
		return e.Ref
	case "binop":
		if e.BinOp == nil {
			return ""
		}
		return fmt.Sprintf("%s %s %s", emitRxExprWithEventBindings(&e.BinOp.Left, bindings), e.BinOp.Op, emitRxExprWithEventBindings(&e.BinOp.Right, bindings))
	case "cond":
		if e.Cond == nil {
			return ""
		}
		return fmt.Sprintf(
			"(%s ? %s : %s)",
			emitRxExprWithEventBindings(&e.Cond.Condition, bindings),
			emitRxExprWithEventBindings(&e.Cond.Then, bindings),
			emitRxExprWithEventBindings(&e.Cond.Else, bindings),
		)
	case "call":
		if e.Call == nil {
			return ""
		}
		return emitCall(e.Call, bindings)
	default:
		return ""
	}
}

func emitCall(c *nir.Call, bindings eventBindings) string {
	args := make([]string, len(c.Args))
	for i := range c.Args {
		args[i] = emitRxExprWithEventBindings(&c.Args[i], bindings)
	}
	if len(args) == 0 {
		return c.Callee + "()"
	}
	receiver := args[0]
	switch c.Callee {
	case "len":
		return receiver + ".count"
	case "upper":
		return receiver + ".uppercased()"
	case "lower":
		return receiver + ".lowercased()"
	case "trim":
		return receiver + ".trimmingCharacters(in: .whitespacesAndNewlines)"
	case "split":
		if len(args) != 2 {
			return receiver
		}
		return receiver + ".components(separatedBy: " + args[1] + ")"
	case "join":
		if len(args) != 2 {
			return receiver
		}
		return receiver + ".joined(separator: " + args[1] + ")"
	case "replace":
		if len(args) != 3 {
			return receiver
		}
		return receiver + ".replacingOccurrences(of: " + args[1] + ", with: " + args[2] + ")"
	case "substring":
		if len(args) != 3 {
			return receiver
		}
		return "String(" + receiver + ".dropFirst(" + args[1] + ").prefix(" + args[2] + " - " + args[1] + "))"
	case "startsWith":
		if len(args) != 2 {
			return receiver
		}
		return receiver + ".hasPrefix(" + args[1] + ")"
	case "endsWith":
		if len(args) != 2 {
			return receiver
		}
		return receiver + ".hasSuffix(" + args[1] + ")"
	case "contains":
		if len(args) != 2 {
			return receiver
		}
		return receiver + ".contains(" + args[1] + ")"
	case "toString":
		return "String(" + receiver + ")"
	case "toInt":
		return "(Int(" + receiver + ") ?? 0)"
	case "toFloat":
		return "(Double(" + receiver + ") ?? 0)"
	default:
		return fmt.Sprintf("%s(%s)", c.Callee, strings.Join(args, ", "))
	}
}

func emitRxBlock(b nir.RxBlock) string {
	return emitRxBlockWithEventBindings(b, nil)
}

func emitRxBlockWithEventBindings(b nir.RxBlock, bindings eventBindings) string {
	parts := make([]string, 0, len(b.Stmts))
	for _, s := range b.Stmts {
		switch s.Kind {
		case "expr":
			parts = append(parts, emitRxExprWithEventBindings(s.Expr, bindings))
		case "signal_set":
			parts = append(parts, fmt.Sprintf("%s = %s", s.Target, emitRxExprWithEventBindings(s.Value, bindings)))
		}
	}
	return strings.Join(parts, "; ")
}

func attrExpr(n *nir.Element, name string) *nir.RxExpr {
	for i := range n.Attrs {
		if n.Attrs[i].Name == name {
			return &n.Attrs[i].Value
		}
	}
	return nil
}

func literalAttr(n *nir.Element, name string) string {
	expr := attrExpr(n, name)
	if expr == nil || expr.Kind != "literal" || expr.Literal == nil {
		return ""
	}
	return expr.Literal.Value
}
