// Code generated by gsxnative. DO NOT EDIT.
package generated

import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.material3.Button
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.setValue
import com.gosx.nativekit.GSXComponent
import com.gosx.nativekit.rememberGSXSignal

data class ExpressionsProps(
    val title: String,
    val count: Int,
    val price: String,
    val tags: List<String>
)

@GSXComponent
@Composable
fun Expressions(props: ExpressionsProps) {
    var title by rememberGSXSignal(props.title)
    var count by rememberGSXSignal(props.count)
    var status by rememberGSXSignal("")
    val normalized = title.trim().replace(" ", "-").lowercase()
    val countText = count.toString()
    val adjustedCount = (countText.toIntOrNull() ?: 0) + 2
    val price = (props.price.toDoubleOrNull() ?: 0.0)
    val tagLine = props.tags.joinToString(separator = ",")
    val hasGo = title.startsWith("Go")
    val hasSX = title.contains("SX")
    val tagCount = props.tags.count()

    Column {
        Button(onClick = { status = (if (count > 0) title.trim().uppercase() else normalized) }) {
            Text(text = "Refresh")
        }
        Text(text = "${status}")
        Text(text = "${normalized}")
        Text(text = "${countText}")
        Text(text = "${adjustedCount}")
        Text(text = "${price}")
        Text(text = "${tagLine}")
        Text(text = "${hasGo}")
        Text(text = "${hasSX}")
        Text(text = "${tagCount}")
    }
}
