// Code generated by gsxnative. DO NOT EDIT.
package generated

import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.material3.Button
import androidx.compose.material3.Checkbox
import androidx.compose.material3.Text
import androidx.compose.material3.TextField
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.input.key.key
import androidx.compose.ui.input.key.onKeyEvent
import com.gosx.nativekit.GSXComponent
import com.gosx.nativekit.rememberGSXSignal

data class FormControlsProps(
    val bio: String,
    val enabled: Boolean,
    val selectedIndex: Int
)

@GSXComponent
@Composable
fun FormControls(props: FormControlsProps) {
    var bio by rememberGSXSignal(props.bio)
    var enabled by rememberGSXSignal(props.enabled)
    var lastKey by rememberGSXSignal("")
    var choice by rememberGSXSignal(props.selectedIndex)

    Column {
        TextField(
            value = bio,
            onValueChange = { eventValue -> bio = eventValue },
            placeholder = { Text(text = "Bio") },
            minLines = 3
        )
        Checkbox(
            checked = enabled,
            onCheckedChange = { eventChecked -> enabled = eventChecked }
        )
        TextField(
            value = lastKey,
            onValueChange = { _ -> },
            modifier = Modifier.onKeyEvent { event ->
                val eventKey = event.key.toString()
                lastKey = eventKey
                false
            },
            placeholder = { Text(text = "Press key") }
        )
        Column {
            listOf("One", "Two").forEachIndexed { eventSelectedIndex, option ->
                Button(onClick = { choice = eventSelectedIndex }) {
                    Text(text = if (eventSelectedIndex == choice) "$option (selected)" else option)
                }
            }
        }
        Text(text = "${bio}")
        Text(text = "${enabled}")
        Text(text = "${lastKey}")
        Text(text = "${choice}")
    }
}
