// Code generated by gsxnative. DO NOT EDIT.
package generated

import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.material3.Button
import androidx.compose.material3.Text
import androidx.compose.material3.TextField
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.setValue
import com.gosx.nativekit.GSXComponent
import com.gosx.nativekit.rememberGSXSignal

data class GreeterProps(
    val initialName: String
)

@GSXComponent
@Composable
fun Greeter(props: GreeterProps) {
    var name by rememberGSXSignal(props.initialName)

    Column {
        TextField(
            value = name,
            onValueChange = { eventValue -> name = eventValue },
            placeholder = { Text(text = "Name") }
        )
        Text(text = "Hello,${name}")
    }
}
