// Code generated by gsxnative. DO NOT EDIT.
package generated

import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.material3.Button
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.setValue
import com.gosx.nativekit.GSXComponent
import com.gosx.nativekit.rememberGSXSignal

data class PanelProps(
    val start: Int,
    val label: String
)

@GSXComponent
@Composable
fun Panel(props: PanelProps) {
    var count by rememberGSXSignal(props.start)
    var label by rememberGSXSignal(props.label)

    Column {
        Text(text = "${label}")
        Row {
            Button(onClick = { count = props.start; label = props.label }) {
                Text(text = "Reset")
            }
            Text(text = "${count}")
            Button(onClick = { count = count + 1 }) {
                Text(text = "+")
            }
            Button(onClick = { count = count + 1; label = "advanced" }) {
                Text(text = "Go")
            }
        }
    }
}
