// Code generated by gsxnative. DO NOT EDIT.
package generated

import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.material3.Button
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.setValue
import com.gosx.nativekit.GSXComponent
import com.gosx.nativekit.rememberGSXSignal

data class BadgeProps(
    val label: String
)

@GSXComponent
@Composable
fun Badge(props: BadgeProps) {
    Text(text = "${props.label}")
}

data class ProfileProps(
    val name: String
)

@GSXComponent
@Composable
fun Profile(props: ProfileProps) {
    Column {
        Badge(props = BadgeProps(label = props.name))
    }
}
