// Code generated by gsxnative. DO NOT EDIT.
package generated

import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.material3.Button
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.setValue
import com.gosx.nativekit.GSXComponent
import com.gosx.nativekit.rememberGSXSignal

data class RosterProps(
    val items: List<String>
)

@GSXComponent
@Composable
fun Roster(props: RosterProps) {
    Column {
        props.items.forEach { item ->
            Text(text = "${item}")
        }
    }
}
