// Code generated by gsxnative. DO NOT EDIT.
package generated

import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.material3.Button
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.setValue
import com.gosx.nativekit.GSXComponent
import com.gosx.nativekit.rememberGSXSignal

data class ToggleProps(
    val initiallyVisible: Boolean
)

@GSXComponent
@Composable
fun Toggle(props: ToggleProps) {
    var visible by rememberGSXSignal(props.initiallyVisible)

    Column {
        if (visible) {
            Text(text = "Visible")
        }
        Button(onClick = { visible = false }) {
            Text(text = "Hide")
        }
    }
}
