// Code generated by gsxnative. DO NOT EDIT.
package generated

import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.material3.Button
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.setValue
import com.gosx.nativekit.GSXComponent
import com.gosx.nativekit.GSXScene3D
import com.gosx.nativekit.GSXScene3DNode
import com.gosx.nativekit.GSXScene3DScene
import com.gosx.nativekit.gsxScene3DSpreadBool
import com.gosx.nativekit.gsxScene3DSpreadFloat
import com.gosx.nativekit.gsxScene3DSpreadInt
import com.gosx.nativekit.gsxScene3DSpreadString
import com.gosx.nativekit.rememberGSXSignal

data class SpreadDemoProps(
    val mesh: Map<String, Any?>
)

@GSXComponent
@Composable
fun SpreadDemo(props: SpreadDemoProps) {
    GSXScene3D(scene = GSXScene3DScene(
        width = 640.0,
        height = 360.0,
        background = "#101820",
        nodes = listOf(
            GSXScene3DNode(id = gsxScene3DSpreadString(props.mesh, "id", ""), tag = "mesh", kind = gsxScene3DSpreadString(props.mesh, "kind", ""), color = gsxScene3DSpreadString(props.mesh, "color", "#8de1ff"), x = gsxScene3DSpreadFloat(props.mesh, "x", 0.0), y = gsxScene3DSpreadFloat(props.mesh, "y", 0.0), z = gsxScene3DSpreadFloat(props.mesh, "z", 0.0), width = gsxScene3DSpreadFloat(props.mesh, "width", 1.0), height = gsxScene3DSpreadFloat(props.mesh, "height", 1.0), depth = gsxScene3DSpreadFloat(props.mesh, "depth", 1.0), count = gsxScene3DSpreadInt(props.mesh, "count", 0), size = gsxScene3DSpreadFloat(props.mesh, "size", 0.0)),
        )
    ))
}
