// Code generated by gsxnative. DO NOT EDIT.
import GSXNativeKit
import SwiftUI

public struct CanvasBackendDemo: GSXComponent {
    public struct Props {
    }
    public let props: Props

    public init(props: Props) {
        self.props = props
    }

    public var body: some View {
        GSXScene3DView(scene: GSXScene3DScene(
            width: 640,
            height: 360,
            background: "#101820",
            backend: .canvas,
            nodes: [
                GSXScene3DNode(id: "hero", tag: "mesh", kind: "box", color: "#8de1ff", x: 0, y: 0, z: 0, width: 1.4, height: 1.0, depth: 0.7, count: 0, size: 0)
            ]
        ))
    }
}
