// Code generated by gsxnative. DO NOT EDIT.
package generated

import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.material3.Button
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.setValue
import com.gosx.nativekit.GSXComponent
import com.gosx.nativekit.GSXScene3D
import com.gosx.nativekit.GSXScene3DBackend
import com.gosx.nativekit.GSXScene3DNode
import com.gosx.nativekit.GSXScene3DScene
import com.gosx.nativekit.rememberGSXSignal

class CanvasBackendDemoProps

@GSXComponent
@Composable
fun CanvasBackendDemo(props: CanvasBackendDemoProps) {
    GSXScene3D(scene = GSXScene3DScene(
        width = 640.0,
        height = 360.0,
        background = "#101820",
        backend = GSXScene3DBackend.Canvas,
        nodes = listOf(
            GSXScene3DNode(id = "hero", tag = "mesh", kind = "box", color = "#8de1ff", x = 0.0, y = 0.0, z = 0.0, width = 1.4, height = 1.0, depth = 0.7, count = 0, size = 0.0),
        )
    ))
}
