// Code generated by gsxnative. DO NOT EDIT.
import GSXNativeKit
import SwiftUI

public struct ParticleDemo: GSXComponent {
    public struct Props {
    }
    public let props: Props

    public init(props: Props) {
        self.props = props
    }

    public var body: some View {
        GSXScene3DView(scene: GSXScene3DScene(
            width: 640,
            height: 360,
            background: "#101820",
            nodes: [
                GSXScene3DNode(id: "sparks", tag: "computeParticles", kind: "spiral", color: "#ffd48f", x: 0, y: 0.2, z: 0, width: 1, height: 1, depth: 1, count: 128, size: 0.12)
            ]
        ))
    }
}
