// Code generated by gsxnative. DO NOT EDIT.
import GSXNativeKit
import SwiftUI

public struct SpreadDemo: GSXComponent {
    public struct Props {
        public var mesh: [String: Any]
    }
    public let props: Props

    public init(props: Props) {
        self.props = props
    }

    public var body: some View {
        GSXScene3DView(scene: GSXScene3DScene(
            width: 640,
            height: 360,
            background: "#101820",
            nodes: [
                GSXScene3DNode(id: gsxScene3DSpreadString(props.mesh, "id", ""), tag: "mesh", kind: gsxScene3DSpreadString(props.mesh, "kind", ""), color: gsxScene3DSpreadString(props.mesh, "color", "#8de1ff"), x: gsxScene3DSpreadFloat(props.mesh, "x", 0.0), y: gsxScene3DSpreadFloat(props.mesh, "y", 0.0), z: gsxScene3DSpreadFloat(props.mesh, "z", 0.0), width: gsxScene3DSpreadFloat(props.mesh, "width", 1.0), height: gsxScene3DSpreadFloat(props.mesh, "height", 1.0), depth: gsxScene3DSpreadFloat(props.mesh, "depth", 1.0), count: gsxScene3DSpreadInt(props.mesh, "count", 0), size: gsxScene3DSpreadFloat(props.mesh, "size", 0.0))
            ]
        ))
    }
}
