// Code generated by gsxnative. DO NOT EDIT.
import GSXNativeKit
import SwiftUI

public struct PostFXDemo: GSXComponent {
    public struct Props {
        public var width: Int
        public var height: Int
    }
    public let props: Props

    public init(props: Props) {
        self.props = props
    }

    public var body: some View {
        GSXScene3DView(scene: GSXScene3DScene(
            width: Double(props.width),
            height: Double(props.height),
            background: "#080f1f",
            postEffects: [
                GSXScene3DPostEffect(kind: "bloom", threshold: 0.72, intensity: 1.4, radius: 0.25, scale: 0.5, saturation: 0, contrast: 0, exposure: 0, mode: "", focusDistance: 0, aperture: 0, maxBlur: 0),
                GSXScene3DPostEffect(kind: "vignette", threshold: 0, intensity: 0.35, radius: 0, scale: 0, saturation: 0, contrast: 0, exposure: 0, mode: "", focusDistance: 0, aperture: 0, maxBlur: 0),
                GSXScene3DPostEffect(kind: "colorGrade", threshold: 0, intensity: 0, radius: 0, scale: 0, saturation: 1.1, contrast: 1.05, exposure: 0.08, mode: "", focusDistance: 0, aperture: 0, maxBlur: 0),
                GSXScene3DPostEffect(kind: "toneMapping", threshold: 0, intensity: 0, radius: 0, scale: 0, saturation: 0, contrast: 0, exposure: 1.0, mode: "aces", focusDistance: 0, aperture: 0, maxBlur: 0)
            ],
            nodes: [
                GSXScene3DNode(id: "hero", tag: "mesh", kind: "box", color: "#8de1ff", x: 0, y: 0, z: 0, width: 1.4, height: 1.0, depth: 0.7, count: 0, size: 0)
            ]
        ))
    }
}
