// Code generated by gsxnative. DO NOT EDIT.
import GSXNativeKit
import SwiftUI

public struct HTMLDemo: GSXComponent {
    public struct Props {
    }
    public let props: Props

    public init(props: Props) {
        self.props = props
    }

    public var body: some View {
        GSXScene3DView(scene: GSXScene3DScene(
            width: 640,
            height: 360,
            background: "#081119",
            htmlOverlays: [
                GSXScene3DHTMLOverlay(id: "hud", html: "<aside class=\"scene-hud__card\"><strong>Hull</strong><span>stable</span></aside>", className: "scene-hud", x: 0, y: 1.1, z: 0.2, width: 1.6, height: 0.8, opacity: 0.95, offsetX: 0, offsetY: 0, pointerEvents: "auto")
            ],
            nodes: [
                GSXScene3DNode(id: "hero", tag: "mesh", kind: "box", color: "#8de1ff", x: 0, y: 0, z: 0, width: 1.4, height: 1.0, depth: 0.7, count: 0, size: 0)
            ]
        ))
    }
}
