// Code generated by gsxnative. DO NOT EDIT.
import GSXNativeKit
import SwiftUI

public struct InstancingDemo: GSXComponent {
    public struct Props {
    }
    public let props: Props

    public init(props: Props) {
        self.props = props
    }

    public var body: some View {
        GSXScene3DView(scene: GSXScene3DScene(
            width: 640,
            height: 360,
            background: "#101820",
            nodes: [
                GSXScene3DNode(id: "asteroids", tag: "instancedMesh", kind: "box", color: "#f7c76b", x: 0, y: 0, z: 0, width: 0.8, height: 0.5, depth: 0.4, count: 3, size: 0)
            ]
        ))
    }
}
